version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/MakeMyDay/front-end

    steps:
      - checkout:
          path: ~/MakeMyDay
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy:
    machine:
      enabled: true

    working_directory: ~/MakeMyDay/front-end

    steps:
      - add_ssh_keys:
          fingerprints:
            - "8f:ba:27:de:59:7d:77:a5:57:d6:ec:b2:f9:2c:26:b1"
      - checkout:
          path: ~/MakeMyDay
      - run:
          name: Push Main to Production
          command: |
            git push https://github.com/byeongjae-kang/MakeMyDay main:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
