DROP TABLE IF EXISTS tasks CASCADE;
CREATE TABLE tasks (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  priority NUMERIC NOT NULL DEFAULT 2,
  status VARCHAR(255) NOT NULL DEFAULT 'In Progress',
  "end" DATE NOT NULL DEFAULT CURRENT_DATE+5,
  start DATE NOT NULL DEFAULT CURRENT_DATE);