DROP TABLE IF EXISTS tasks CASCADE;
CREATE TABLE tasks (
  id SERIAL PRIMARY KEY NOT NULL,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  name VARCHAR(255),
  description VARCHAR(255),
  priority NUMERIC NOT NULL DEFAULT 2,
  status VARCHAR(255) NOT NULL DEFAULT 'In Progress',
  "end" DATE NOT NULL DEFAULT CURRENT_DATE+5,
  start DATE NOT NULL DEFAULT CURRENT_DATE);