DROP TABLE IF EXISTS tasks CASCADE;
CREATE TABLE tasks (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  description VARCHAR(255),
  priority NUMERIC DEFAULT 3,
  status VARCHAR(255) DEFAULT 'In Progress',
  start_date DATE DEFAULT CURRENT_DATE,
  due_date DATE);